apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grilotv-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grilotv-app
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grilotv-postgres
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grilotv-postgres
