apiVersion: v1
kind: Secret
metadata:
  name: grilotv-secrets
type: Opaque
stringData:
  NEXTAUTH_SECRET: "troque-esta-chave-antes-de-subir"
  POSTGRES_PASSWORD: "troque-esta-senha-do-postgres"
  DATABASE_URL: "postgresql://grilotv:troque-esta-senha-do-postgres@grilotv-postgres:5432/iptv?schema=public"
  SEED_ADMIN_EMAIL: "admin@grilotv.online"
  SEED_ADMIN_PASSWORD: "troque-a-senha-do-admin"
  SEED_MP_ACCESS_TOKEN: ""
  SEED_EXPFY_PUBLIC_KEY: ""
  SEED_EXPFY_SECRET_KEY: ""
